services: 
    main:
        build: 
            context: .
            dockerfile: Dockerfile
        command: 'php artisan serve --host=0.0.0.0'
        volumes:
            - .:/app
        ports:
            - 8000:8000
        depends_on: 
            - db

    db:
        platform: linux/x86_64
        image: mysql:8.0
        environment: 
            MYSQL_DATABASE: flashcard
            MYSQL_USER: sail
            MYSQL_ROOT: root
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - 3306:3306
